project:
  type: default
  output-dir: .

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    theme: [cosmo, custom.scss]
    code-copy: true
    code-overflow: wrap
    highlight-style: github-dark
    smooth-scroll: true
    self-contained: true
    link-external-newwindow: true
    mainfont: "system-ui, -apple-system, sans-serif"
